// <auto-generated />
using Equipodetrabajolabo3.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Equipodetrabajolabo3.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240504081051_addEquiposTableToDb")]
    partial class addEquiposTableToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("Equipodetrabajolabo3.Models.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("detalles")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("equipos");
                });
#pragma warning restore 612, 618
        }
    }
}
